theme: jekyll-theme-cayman
title: The IoT-Bench Repository
description: A community effort to better evaluate and compare low-power wireless networks
github:
  is_project_page: true

collections:
  profiles:
    output: true
  protocols:
    output: true
  environments:
    output: true
  results:
    output: true
  metrics:
    output: true
    permalink: /:collection/:name

defaults:
  - scope:
      path: ""
    values:
      layout: default
